import { PageHeader, Card } from '../components/ui'

export default function ApiDocs() {
  return (
    <div>
      <PageHeader title="API Documentation" subtitle="Interactive OpenAPI docs, auto-generated by FastAPI" />
      <Card>
        <p className="text-sm text-slate-700 mb-4">
          FastAPI serves interactive Swagger UI and ReDoc documentation directly — nothing to hand-maintain
          here. With the backend running:
        </p>
        <ul className="text-sm space-y-2">
          <li>
            <a href="/docs" target="_blank" rel="noreferrer" className="text-blue-600 font-medium">
              /docs
            </a>{' '}
            — Swagger UI (try endpoints directly from the browser)
          </li>
          <li>
            <a href="/redoc" target="_blank" rel="noreferrer" className="text-blue-600 font-medium">
              /redoc
            </a>{' '}
            — ReDoc reference documentation
          </li>
          <li>
            <a href="/openapi.json" target="_blank" rel="noreferrer" className="text-blue-600 font-medium">
              /openapi.json
            </a>{' '}
            — raw OpenAPI schema, for generating client SDKs
          </li>
        </ul>
        <p className="text-xs text-muted mt-4">
          These links resolve against the backend's own origin (not this frontend's dev server) — if you're
          running the frontend on :5173 and backend on :8000, open http://localhost:8000/docs directly.
        </p>
      </Card>
    </div>
  )
}
